version: "3.3"
services:
    group-actual:
        container_name: group-actual
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: group-actual:1
        restart: unless-stopped
        ports: 
            - "8088:80"
        volumes:
            - .:/app
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        healthcheck:
            test: bash -c "[ -f /app/vendor/autoload.php ]"
            timeout: 10s
            retries: 30